function Cg = getCg(rocket, motor, propMass)

Cg = (rocket.structure.finMass*(rocket.structure.length-rocket.fin.height/2)*rocket.fin.numFins + ...
    rocket.structure.tubeMass*rocket.structure.length/2 + ...
    rocket.structure.electronicsMass*rocket.structure.electronicsCg + ...
    rocket.structure.ballastMass*rocket.structure.ballastCg + ...
    motor.dryMass*motor.height/2 + propMass*motor.height/2)/...
    (rocket.structure.dryMass + motor.dryMass + propMass);

end